name-template: $RESOLVED_VERSION
tag-template: $RESOLVED_VERSION
template: $CHANGES
change-template: '- $TITLE ([#$NUMBER](https://github.com/Parsely/wp-parsely/pull/$NUMBER))'
categories:
  - title: Added
    labels:
      - 'Changelog: Added'
  - title: Changed
    labels:
      - 'Changelog: Changed'
  - title: Deprecated
    labels:
      - 'Changelog: Deprecated'
  - title: Removed
    labels:
    - 'Changelog: Removed'
  - title: Fixed
    labels:
      - 'Changelog: Fixed'
  - title: Security
    labels:
      - 'security'
      - 'Changelog: Security'
  - title: Dependency Updates
    labels:
      - 'Component: Dependencies'

version-resolver:
  major:
    labels:
      - 'Changelog: Removed'
  minor:
    labels:
      - 'Changelog: Added'
      - 'Changelog: Deprecated'
  patch:
    labels:
      - 'Changelog: Fixed'
      - 'Changelog: Security'
      - 'Component: Dependencies'

exclude-labels:
  - 'Changelog: Skip'
