# Release Drafter configuration file.

# Name of the created release draft.
name-template: $RESOLVED_VERSION

# Name of the created tag.
tag-template: $RESOLVED_VERSION

# The release draft's text, which is the list of merged PRs.
template: $CHANGES

# Template for every PR added to the changelog as a line.
change-template: '- $TITLE ([#$NUMBER](https://github.com/Parsely/wp-parsely/pull/$NUMBER))'

# Changelog sections and their respective labels.
# For example, all PRs with the "Changelog: Added" label will be inserted within
# the changelog's "Added" section.
categories:
  - title: Added
    labels:
      - 'Changelog: Added'
  - title: Changed
    labels:
      - 'Changelog: Changed'
  - title: Deprecated
    labels:
      - 'Changelog: Deprecated'
  - title: Removed
    labels:
    - 'Changelog: Removed'
  - title: Fixed
    labels:
      - 'Changelog: Fixed'
  - title: Security
    labels:
      - 'security'
      - 'Changelog: Security'
  - title: Dependency Updates
    labels:
      - 'Component: Dependencies'

# Labels that will exclude PRs from the changelog.
exclude-labels:
  - 'Changelog: Skip'

# Automatic release draft version bumping based on PR labels.
# For example, if the changeset includes an "Added" label, a minor version bump
# will occur. However, if there's also a "Removed" label, a major version bump
# will occur.
version-resolver:
  major:
    labels:
      - 'Changelog: Removed'
  minor:
    labels:
      - 'Changelog: Added'
      - 'Changelog: Deprecated'
  patch:
    labels:
      - 'Changelog: Fixed'
      - 'Changelog: Security'
      - 'Component: Dependencies'
