export const RECOMMENDED_BLOCK_ERROR = 'RECOMMENDED_BLOCK_ERROR';
export const RECOMMENDED_BLOCK_LOADED = 'RECOMMENDED_BLOCK_LOADED';
export const RECOMMENDED_BLOCK_RECOMMENDATIONS = 'RECOMMENDED_BLOCK_RECOMMENDATIONS';
