name: Deploy to WordPress.org
on: workflow_dispatch
jobs:
  tag:
    name: New tag
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Build # Remove or modify this step as needed
        run: |
          npm ci
          npm run build
      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
