name: End-to-end (e2e) Tests - Playwright

on:
  # Run on all pull requests.
  pull_request:
  push:
    branches:
      - trunk

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name for pull requests
  # or the commit hash for any other events.
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  test:
    name: e2e against WordPress latest
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Refresh Composer autoload files
        run: composer dump-autoload --classmap-authoritative

      - name: Use desired version of NodeJS
        uses: actions/setup-node@v4.0.3
        with:
          node-version: 16
          cache: npm

      - name: Npm install
        run: |
          npm ci

      - name: Install Playwright dependencies
        run: |
          npx playwright install chromium --with-deps

      - name: Start up WordPress environment
        run: |
          npm run dev:start

      - name: Running the tests
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
        run: |
          npm run test:e2e:playwright

      - name: Stop WordPress environment
        run: |
          npm run dev:stop

      - name: Archive e2e results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: test-results
          path: artifacts
