name: Integration Tests

on:
  # Run on all pushes and on all pull requests.
  # Prevent the "push" build from running when there are only irrelevant changes.
  push:
    paths-ignore:
      - '**.md'
  pull_request:
  # Allow manually triggering the workflow.
  workflow_dispatch:

jobs:
  test:
    name: PHP ${{ matrix.php }}
    # ubuntu-20.04 / ubuntu-latest includes MySQL 8, which has issues with older versions of PHP.
    # ubuntu-18.04 includes PHP versions 7.1-8.0, but 5.6-7.1 are cached, so setup is about 5 seconds.
    # See https://setup-php.com/i/452
    runs-on: ubuntu-18.04

    env:
      WP_VERSION: latest

    strategy:
      # PHP 5.6 uses PHPUnit 5.7.27
      # PHP 7.0 uses PHPUnit 6.5.14
      # PHP 7.1 uses PHPUnit 7.5.20
      # PHP 7.2 uses PHPUnit 8.5.21
      # PHP 7.3 uses PHPUnit 9.5.10
      # PHP 7.4 uses PHPUnit 9.5.10
      # PHP 8.0 uses PHPUnit 9.5.10
      # PHP 8.1 uses PHPUnit 9.5.10
      matrix:
        php: ['5.6', '7.0', '7.1', '7.2', '7.3', '7.4']
        include:
          - php: '8.0'
            # Ignore platform requirements, so that PHPUnit 7.5 can be installed on PHP 8.0 (and above).
#            composer-options: '--ignore-platform-reqs'
            extensions: pcov
            ini-values: pcov.directory=., "pcov.exclude=\"~(vendor|tests)~\""
            coverage: pcov
          # There is no PHP nightly. Due to https://github.com/sebastianbergmann/phpunit/issues/4575 this is never
          # going to succeed as WordPress is hard-coded to only support PHPUnit 7.5, and then fix only appears
          # in PHPUnit 8.5.14.
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ matrix.extensions }}
          ini-values: ${{ matrix.ini-values }}
          coverage: ${{ matrix.coverage }}

      - name: Setup problem matchers for PHP
        run: echo "::add-matcher::${{ runner.tool_cache }}/php.json"

      - name: Setup Problem Matchers for PHPUnit
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v1
        with:
          composer-options: '${{ matrix.composer-options }}'

      - name: Start MySQL Service
        run: sudo systemctl start mysql.service

      - name: Prepare environment for integration tests
        run: composer prepare-ci

      - name: Run integration tests (single site)
        if: ${{ matrix.php != 8.0 }}
        run: composer test
      - name: Run integration tests (single site with code coverage)
        if: ${{ matrix.php == 8.0 }}
        run: composer coverage-ci
      - name: Run integration tests (multisite)
        run: composer test-ms
