name: Integration Tests

on:
  # Run on all pushes and on all pull requests.
  # Prevent the "push" build from running when there are only irrelevant changes.
  push:
    paths-ignore:
      - '**.md'
  pull_request:

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: PHP ${{ matrix.php }}
    runs-on: ubuntu-20.04

    env:
      WP_VERSION: latest

    strategy:
      # PHP 7.1 uses PHPUnit 7.5.20
      # PHP 7.2 uses PHPUnit 8.5.21
      # PHP 7.3 uses PHPUnit 9.5.10
      # PHP 7.4 uses PHPUnit 9.5.10
      # PHP 8.0 uses PHPUnit 9.5.10
      # PHP 8.1 uses PHPUnit 9.5.10
      # Keys:
      # - coverage: Whether to run the tests with code coverage.
      # - experimental: Whether the build is "allowed to fail".
      matrix:
        php: ['7.1', '7.2', '7.3', '7.4']
        coverage: [none]
        experimental: [false]
        include:
          # Separate out PHP 8.0, so it can run with code coverage.
          - php: '8.0'
            coverage: pcov
            extensions: pcov
            ini-values: pcov.directory=., "pcov.exclude=\"~(vendor|tests)~\""
            experimental: false
          - php: '8.1'
            coverage: none
            experimental: false
          # - php: '8.2'
          #  coverage: none
          #  experimental: true
      fail-fast: false
    continue-on-error: ${{ matrix.experimental }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@14dc64f30986eaa2ad2dddcec073f5aab18e5a24 # v1
        with:
          allowed-endpoints:
            api.github.com:443
            artifactcache.actions.githubusercontent.com:443
            codeload.github.com:443
            develop.svn.wordpress.org:443
            github.com:443
            kv4gacprodeus2file3.blob.core.windows.net:443
            objects.githubusercontent.com:443
            packagist.org:443
            raw.github.com:443
            repo.packagist.org:443
            wordpress.org:443

      - name: Checkout code
        uses: actions/checkout@629c2de402a417ea7690ca6ce3f33229e27606a5 # v2

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@cf8b3c07b614e754f66e055af0e3498701349be9 # v2
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ matrix.extensions }}
          ini-values: ${{ matrix.ini-values }}
          coverage: ${{ matrix.coverage }}

      - name: Setup problem matchers for PHP
        run: echo "::add-matcher::${{ runner.tool_cache }}/php.json"

      - name: Setup Problem Matchers for PHPUnit
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install Composer dependencies
        uses: ramsey/composer-install@f680dac46551dffb2234a240d65ae806c2999dd6 # v2

      # - name: Install Composer dependencies for PHP >= 8.2
      #  if: ${{ matrix.php >= 8.2 }}
      #  uses: ramsey/composer-install@f680dac46551dffb2234a240d65ae806c2999dd6 # v2
      #  with:
      #    composer-options: --ignore-platform-reqs

      - name: Start MySQL Service
        run: sudo systemctl start mysql.service

      - name: Setting mysql_native_password for PHP <= 7.3
        if: ${{ matrix.php <= 7.3 }}
        run: mysql -u root -proot -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root';"

      - name: Prepare environment for integration tests
        run: composer prepare-ci --no-interaction

      - name: Run integration tests (single site)
        if: ${{ matrix.php != 8.0 }}
        run: composer testwp --no-interaction

      - name: Run integration tests (multi site)
        run: composer testwp-ms --no-interaction

      - name: Run integration tests (multisite site with code coverage)
        if: ${{ matrix.php == 8.0 }}
        run: composer coveragewp-ci --no-interaction
