name: Integration Tests

on:
  # Run on all pushes and on all pull requests.
  # Prevent the "push" build from running when there are only irrelevant changes.
  push:
    paths-ignore:
      - '**.md'
  pull_request:
  # Allow manually triggering the workflow.
  workflow_dispatch:

jobs:
  test:
    name: PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.allowed_failure }}

    env:
      WP_VERSION: latest

    strategy:
      matrix:
        php: [ '5.6', '7.0', '7.1', '7.2', '7.3', '7.4', '8.0' ]
        allowed_failure: [ false ]
        include:
          # PHP nightly.
          - php: '8.1'
            allowed_failure: true
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: pcov
          # https://make.wordpress.org/hosting/handbook/handbook/server-environment/#php-extensions
          extensions: curl, dom, exif, fileinfo, hash, json, mbstring, mysqli, libsodium, openssl, pcre, imagick, xml, zip

      - name: Install Composer dependencies (PHP < 8.0 )
        if: ${{ matrix.php < 8.0 }}
        uses: ramsey/composer-install@v1

      - name: Install Composer dependencies (PHP >= 8.0)
        if: ${{ matrix.php >= 8.0 }}
        uses: ramsey/composer-install@v1
        with:
          composer-options: --ignore-platform-reqs

      - name: Setup Problem Matchers for PHPUnit
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

#      - name: Run unit tests
#        run: composer unit

      - name: Start MySQL Service
        run: sudo systemctl start mysql.service

      - name: Switch to use mysql_native_password for PHP < 7.4
        if: ${{ matrix.php < 7.4 }}
        # Info https://www.php.net/manual/en/mysqli.requirements.php
        run: mysql -u root -p"root" -e "ALTER USER 'root'@localhost IDENTIFIED WITH mysql_native_password BY 'root'";  

      - name: Prepare environment for integration tests
        run: composer prepare

      - name: Run integration tests (single site)
        run: composer integration
      - name: Run integration tests (multisite)
        run: composer integration-ms
