# This workflow will do a clean install of node dependencies, build the source code and run tests.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  pull_request:
  push:
    paths:
      - .github/workflows/*.js.yml
      - '**/*[tj]sx?'
      - package*.json

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    permissions:
      contents: read # for actions/checkout to fetch code
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@14dc64f30986eaa2ad2dddcec073f5aab18e5a24 # v1
        with:
          allowed-endpoints:
            artifactcache.actions.githubusercontent.com:443
            github.com:443
            kv4gacprodeus2file3.blob.core.windows.net:443
            registry.npmjs.org:443
            storage.googleapis.com:443

      - name: Checkout code
        uses: actions/checkout@629c2de402a417ea7690ca6ce3f33229e27606a5 # v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561 # v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install JavaScript dependencies
        run: npm ci

      - name: Lint CSS code
        run: npm run lint:css

      - name: Lint package.json file
        run: npm run lint:pkg-json

      - name: Lint JS code
        run: npm run lint:js

      - name: Build application
        run: npm run build

      - name: Confirm the build is up-to-date
        run: |
          REPOSTATUS=`git status --porcelain 2>/dev/null`;
          if [[ -n "$REPOSTATUS" ]]; then
            echo "Repo is not clean. Did you forget to commit changes to the /build dir?";
            echo "$REPOSTATUS";
            exit 1;
          else
            echo "The repo file system is clean (build files are present and up to date).";
          fi

      - name: Run tests
        run: npm test
