name: Update version numbers and changelog and push them to trunk

on:
  release:
    types: [prereleased]

jobs:
  update:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.release.target_commitish }}
          token: ${{ secrets.PUBLIC_REPO_PERMISSION }}

      - name: Bump version numbers
        run: |
          NEW_VERSION=$(git describe --tags --abbrev=0)
          sed -i "s/Stable tag: .*  $/Stable tag: $NEW_VERSION  /" README.md
          sed -i "s/\"version\": \".*\"/\"version\": \"$NEW_VERSION\"/" package.json
          sed -i "s/export const PLUGIN_VERSION = '.*'/export const PLUGIN_VERSION = '$NEW_VERSION'/" tests/e2e/utils.js
          sed -i "s/ \* Version:           .*$/ \* Version:           $NEW_VERSION/" wp-parsely.php
          sed -i "s/const PARSELY_VERSION = '.*'/const PARSELY_VERSION = '$NEW_VERSION'/" wp-parsely.php
          npm install

      - name: Add latest release notes to changelog
        uses: stefanzweifel/changelog-updater-action@v1.6.0
        with:
          latest-version: ${{ github.event.release.tag_name }}
          release-notes: ${{ github.event.release.body }}

      - name: Add comparison URL to changelog
        run: |
          TAG_PREVIOUS=$(git describe --abbrev=0 --tags $(git rev-list --tags --skip=1 --max-count=1))
          sed -i -e "0,/$TAG_NEW/ s+$TAG_NEW+\[&\]\(https\:\/\/github\.com\/Parsely\/wp\-parsely\/compare\/$TAG_PREVIOUS\.\.\.$TAG_NEW\)+" CHANGELOG.md
        env:
          TAG_NEW: ${{ github.event.release.tag_name }}

      - name: Remove pull request protection from trunk branch
        uses: octokit/request-action@v2.1.6
        with:
          route: DELETE /repos/Parsely/wp-parsely/branches/trunk/protection/required_pull_request_reviews
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLIC_REPO_PERMISSION }}

      - name: Commit version bump and changelog to trunk
        uses: stefanzweifel/git-auto-commit-action@v4.14.1
        with:
          branch: trunk
          commit_message: Bump plugin version to ${{ github.event.release.tag_name }} and update changelog
          file_pattern: CHANGELOG.md README.md package-lock.json package.json tests/e2e/utils.js wp-parsely.php
          commit_options: '--no-verify'

      - name: Re-add pull request protection to trunk branch
        uses: octokit/request-action@v2.1.6
        with:
          route: PATCH /repos/Parsely/wp-parsely/branches/trunk/protection/required_pull_request_reviews
          dismiss_stale_reviews: true
          require_code_owner_reviews: true
          required_approving_review_count: 1
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLIC_REPO_PERMISSION }}
